I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 62, in script
    "%(randAbility)n"
ValueError: unsupported format character 'n' (0x6e) at index 14

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 62, in script
    "%(randAbility)n"
  File "D:\Ren'py\renpy\ast.py", line 613, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "D:\Ren'py\renpy\exports.py", line 1139, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character 'n' (0x6e) at index 14

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Adventure 1.0
